//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Drawing;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("DiscountJournal", Namespace="", IsNullable=false)]
public partial class DiscountJournalType {
    
    private DiscountType[] discountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Discount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DiscountType[] Discount {
        get {
            return this.discountField;
        }
        set {
            this.discountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DiscountType {

    private string shopField;
    
    private int sizeOfDiscountField;
    
    private System.DateTime expirationDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Shop {
        get {
            return this.shopField;
        }
        set {
            this.shopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int SizeOfDiscount {
        get {
            return this.sizeOfDiscountField;
        }
        set {
            this.sizeOfDiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime ExpirationDate {
        get {
            return this.expirationDateField;
        }
        set {
            this.expirationDateField = value;
        }
    }

    public DiscountType() { }
    public DiscountType(string shop, int sizeOfDiscount, DateTime expirationDate)
    {
        Shop = shop;
        SizeOfDiscount = sizeOfDiscount;
        ExpirationDate = expirationDate;
    }
}
